# Generated by Django 5.2.17 on 2026-08-17 12:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sequence', models.PositiveIntegerField()),
                ('total_miles_driving', models.FloatField()),
                ('off_duty_hours', models.FloatField()),
                ('sleeper_hours', models.FloatField()),
                ('driving_hours', models.FloatField()),
                ('on_duty_hours', models.FloatField()),
            ],
            options={
                'ordering': ['trip', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location_text', models.CharField(max_length=255)),
                ('current_lat', models.FloatField()),
                ('current_lon', models.FloatField()),
                ('pickup_location_text', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lon', models.FloatField()),
                ('dropoff_location_text', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lon', models.FloatField()),
                ('current_cycle_used_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start_datetime', models.DateTimeField()),
                ('timezone', models.CharField(default='America/Chicago', max_length=64)),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('route_geometry', models.JSONField()),
                ('cycle_hours_remaining', models.FloatField(blank=True, null=True)),
                ('restart_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=3)),
                ('start_minute', models.PositiveSmallIntegerField()),
                ('end_minute', models.PositiveSmallIntegerField()),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('log_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.logday')),
            ],
            options={
                'ordering': ['log_day', 'start_minute'],
            },
        ),
        migrations.AddField(
            model_name='logday',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('start', 'Trip Start'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel Stop'), ('break_30', '30-Minute Break'), ('rest_10', '10-Hour Reset'), ('restart_34', '34-Hour Restart')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('distance_from_origin_miles', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_stop_sequence_per_trip')],
            },
        ),
        migrations.AddConstraint(
            model_name='logday',
            constraint=models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_log_day_sequence_per_trip'),
        ),
    ]
